import type { Metadata } from "next";
import "./globals.css";
import { globalMetadata } from "@/lib/seo";
import {
  getOrganizationSchema,
  getWebsiteSchema,
  StructuredDataScript,
} from "@/lib/structured-data";

// Export global metadata
export const metadata: Metadata = globalMetadata;

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#7a3e1d",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* 
          ===== CRITICAL SEO TAGS =====
          These are auto-generated by Next.js metadata API above
          But you can add additional meta tags here if needed
        */}

        {/* Preload critical fonts if using Google Fonts */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" /> */}
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" /> */}

        {/* Structured Data - Organization & Website */}
        <StructuredDataScript schema={getOrganizationSchema()} />
        <StructuredDataScript schema={getWebsiteSchema()} />

        {/* 
          Additional SEO optimizations
        */}
        
        {/* Format detection - prevents phone number auto-linking if not wanted */}
        <meta name="format-detection" content="telephone=no" />
        
        {/* Apple specific */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        
        {/* Microsoft specific */}
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="msapplication-config" content="/browserconfig.xml" />
        
        {/* PWA - Display mode */}
        <meta name="mobile-web-app-capable" content="yes" />
        
        {/* 
          DNS Prefetch - speeds up external resource loading
          Optional: Add for third-party services
        */}
        {/* <link rel="dns-prefetch" href="https://fonts.googleapis.com" /> */}
        {/* <link rel="dns-prefetch" href="https://analytics.google.com" /> */}
      </head>

      <body>
        {/* 
          ===== SEMANTIC HTML STRUCTURE =====
          Using semantic tags improves both SEO and accessibility
          
          - <header>: Site header/navigation
          - <main>: Main content (only one per page)
          - <section>: Thematic grouping of content
          - <article>: Self-contained content
          - <aside>: Sidebar/related content
          - <footer>: Site footer
          - Proper heading hierarchy: h1 → h2 → h3 (never skip levels)
        */}
        
        {children}

        {/* 
          ===== PERFORMANCE OPTIMIZATIONS =====
          
          1. Image Optimization:
             - Use Next.js <Image> component (auto WebP, lazy load)
             - Set width/height (prevents CLS)
             - Use priority only for LCP images
          
          2. Font Optimization:
             - System fonts are default (no extra requests)
             - Or use Google Fonts variable fonts with display=swap
          
          3. Core Web Vitals:
             - LCP (Largest Contentful Paint): ✓ Covered by Next.js defaults
             - FID (First Input Delay): ✓ Minimal JS by default
             - CLS (Cumulative Layout Shift): ✓ Image dimensions prevent shift
          
          4. Code Splitting:
             - Use dynamic imports for heavy components
             - Next.js handles route-based code splitting automatically
        */}
      </body>
    </html>
  );
}
